---
title: "Developing Database"
author: "Paige Kemper"
date: "2025-09-25"
output: html_document
---

```{r}

library(knitr)
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  cache = TRUE
)

options(width = 100)
```

```{r}
# Setup for interactive 3D plots (optional)
if (requireNamespace("rgl", quietly = TRUE)) {
  rgl::setupKnitr()
}

# Define the colorize function for use later in the document
 colorize <- function(x, color) {
  sprintf("<span style='color: %s;'>%s</span>", color, x)
}
```

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()


colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
#klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>